name: Lagrange.OneBot Docker Push

on:
  push:
      tags:
        - '*'
      branches:
        - 'master'
      paths:
        - "**.cs"
        - "Dockerfile"
        - "**.csproj"
        - "appsettings.onebot.json"
  workflow_dispatch:

jobs:
  build_push:
     runs-on: ubuntu-latest
     permissions:
        contents: read
        packages: write
     steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/lagrange.onebot
          tags: |
            type=edge
            type=sha,event=branch
            type=ref,event=tag
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64

