name: Upstream Sync and Build

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # every day
  workflow_dispatch:

jobs:
  sync_upstream:
    name: Sync upstream changes
    runs-on: windows-latest
    if: ${{ github.event.repository.fork }}
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: LagrangeDev/Lagrange.Core
          upstream_sync_branch: master
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: Sync check
        if: failure()
        run: |
          exit 1

  build:
    needs: sync_upstream
    name: Build Lagrange.OneBot
    runs-on: windows-latest
    strategy:
      matrix:
        runtimeIdentifier: [ linux-x64, linux-arm64]

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build for ${{ matrix.runtimeIdentifier }}
        shell: powershell
        run: |
          dotnet publish Lagrange.OneBot/Lagrange.OneBot.csproj --no-self-contained -p:PublishSingleFile=true -p:IncludeContentInSingleFile=true -p:RuntimeIdentifier=${{ matrix.runtimeIdentifier }}

      - name: Upload binary files(${{ matrix.runtimeIdentifier }})
        uses: actions/upload-artifact@v3
        with:
          name: Lagrange.OneBot_${{ matrix.runtimeIdentifier }}
          path: Lagrange.OneBot/bin/Debug/net7.0/${{ matrix.runtimeIdentifier }}/publish
